version: '3'

services: 
  python_app:
    container_name: "python_app"
    build: 
      dockerfile: "Dockerfile"
      context: "./build"
      args: 
        - "PYTHON_VERSION=3.9.5"
        - "NODE_VERSION=v15.9.0"
    ports: 
      - "8080:8080"
    volumes: 
      - "./share:/mnt/share"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: /workspace
    tty: true
